// Generated by scripts/generate-provider-model-preferences.mjs from provider-model-preferences.yaml.
// Do not edit this file directly.

export type ProviderModelSettingsVisibility = "simple" | "advanced";

export interface ProviderSettingsPreference {
  provider: string;
  label: string;
  lab: string;
  settingsVisibility: ProviderModelSettingsVisibility;
  defaultEnabled: boolean;
  defaultModel?: string | undefined;
}

export interface ProviderModelPreference {
  provider: string;
  modelId: string;
  settingsVisibility: ProviderModelSettingsVisibility;
  lab: string;
  family?: string | undefined;
  recommended: boolean;
  recommendationReason?: string | undefined;
  defaultForProvider: boolean;
  requiresUnrecommendedWarning: boolean;
}

export const PROVIDER_MODEL_PREFERENCE_SOURCE = {
  "catalogEvidence": {
    "refreshedAt": "2026-04-26",
    "piMonoCommit": "05f79b08",
    "piAiPackageVersion": "0.70.2",
    "sourcePath": "../pi-mono/packages/ai/src/models.generated.ts",
    "packageCatalog": "@mariozechner/pi-ai",
    "piMonoModelsPath": "../pi-mono/packages/ai/src/models.generated.ts"
  },
  "catalogDrift": {
    "missingPreferredModels": [
      {
        "provider": "openai",
        "modelId": "gpt-5.5-pro",
        "requestedLabel": "GPT-5.5 Pro",
        "evidence": "Absent from pi-mono packages/ai/src/models.generated.ts at 05f79b08 and @mariozechner/pi-ai 0.70.2; closest available OpenAI Pro slug is gpt-5.4-pro."
      }
    ]
  }
} as const;

export const PROVIDER_SETTINGS_PREFERENCES = {
  "anthropic": {
    "provider": "anthropic",
    "label": "Anthropic API",
    "lab": "Anthropic",
    "settingsVisibility": "simple",
    "defaultEnabled": true,
    "defaultModel": "claude-opus-4-7"
  },
  "deepseek": {
    "provider": "deepseek",
    "label": "DeepSeek API",
    "lab": "DeepSeek",
    "settingsVisibility": "advanced",
    "defaultEnabled": false,
    "defaultModel": "deepseek-v4-pro"
  },
  "github-copilot": {
    "provider": "github-copilot",
    "label": "GitHub Copilot OAuth",
    "lab": "GitHub Copilot",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "gpt-5.4"
  },
  "google": {
    "provider": "google",
    "label": "Google Gemini API",
    "lab": "Google",
    "settingsVisibility": "simple",
    "defaultEnabled": true,
    "defaultModel": "gemini-3.1-pro-preview"
  },
  "groq": {
    "provider": "groq",
    "label": "Groq",
    "lab": "Groq",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "moonshotai/kimi-k2-instruct"
  },
  "kimi-coding": {
    "provider": "kimi-coding",
    "label": "Kimi Coding",
    "lab": "Moonshot AI",
    "settingsVisibility": "advanced",
    "defaultEnabled": false,
    "defaultModel": "kimi-k2-thinking"
  },
  "openai": {
    "provider": "openai",
    "label": "OpenAI API",
    "lab": "OpenAI",
    "settingsVisibility": "simple",
    "defaultEnabled": true,
    "defaultModel": "gpt-5.5"
  },
  "openai-codex": {
    "provider": "openai-codex",
    "label": "ChatGPT / Codex OAuth",
    "lab": "OpenAI",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "gpt-5.5"
  },
  "opencode": {
    "provider": "opencode",
    "label": "OpenCode Zen",
    "lab": "OpenCode",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "claude-opus-4-7"
  },
  "opencode-go": {
    "provider": "opencode-go",
    "label": "OpenCode Go",
    "lab": "OpenCode",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "kimi-k2.6"
  },
  "openrouter": {
    "provider": "openrouter",
    "label": "OpenRouter",
    "lab": "OpenRouter",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "openai/gpt-5.4"
  },
  "vercel-ai-gateway": {
    "provider": "vercel-ai-gateway",
    "label": "Vercel AI Gateway",
    "lab": "Vercel",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "openai/gpt-5.4"
  },
  "xai": {
    "provider": "xai",
    "label": "xAI",
    "lab": "xAI",
    "settingsVisibility": "simple",
    "defaultEnabled": false,
    "defaultModel": "grok-4.20-0309-reasoning"
  },
  "zai": {
    "provider": "zai",
    "label": "Z.AI API",
    "lab": "Z.AI",
    "settingsVisibility": "advanced",
    "defaultEnabled": false,
    "defaultModel": "glm-5.1"
  }
} as const satisfies Record<string, ProviderSettingsPreference>;

export const PROVIDER_MODEL_PREFERENCES = {
  "anthropic": {
    "claude-opus-4-6": {
      "provider": "anthropic",
      "modelId": "claude-opus-4-6",
      "settingsVisibility": "simple",
      "lab": "Anthropic",
      "family": "Claude Opus",
      "recommended": true,
      "recommendationReason": "Recent Opus fallback with strong reasoning and editing behavior.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "claude-opus-4-7": {
      "provider": "anthropic",
      "modelId": "claude-opus-4-7",
      "settingsVisibility": "simple",
      "lab": "Anthropic",
      "family": "Claude Opus",
      "recommended": true,
      "recommendationReason": "Preferred Anthropic model in the refreshed Pi catalog for high-stakes document review.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    },
    "claude-sonnet-4-6": {
      "provider": "anthropic",
      "modelId": "claude-sonnet-4-6",
      "settingsVisibility": "simple",
      "lab": "Anthropic",
      "family": "Claude Sonnet",
      "recommended": true,
      "recommendationReason": "Balanced Anthropic option for lower-latency professional editing.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    }
  },
  "deepseek": {
    "deepseek-v4-flash": {
      "provider": "deepseek",
      "modelId": "deepseek-v4-flash",
      "settingsVisibility": "advanced",
      "lab": "DeepSeek",
      "family": "DeepSeek V4",
      "recommended": true,
      "recommendationReason": "Direct lower-latency DeepSeek V4 slug; kept Advanced for explicit opt-in.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "deepseek-v4-pro": {
      "provider": "deepseek",
      "modelId": "deepseek-v4-pro",
      "settingsVisibility": "advanced",
      "lab": "DeepSeek",
      "family": "DeepSeek V4",
      "recommended": true,
      "recommendationReason": "Direct DeepSeek V4 Pro slug; kept Advanced because direct regional-provider setup should be intentional.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "github-copilot": {
    "claude-opus-4.6": {
      "provider": "github-copilot",
      "modelId": "claude-opus-4.6",
      "settingsVisibility": "simple",
      "lab": "GitHub Copilot",
      "family": "Claude Opus",
      "recommended": true,
      "recommendationReason": "Copilot-hosted Opus option for companion OAuth mode.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "claude-sonnet-4.6": {
      "provider": "github-copilot",
      "modelId": "claude-sonnet-4.6",
      "settingsVisibility": "simple",
      "lab": "GitHub Copilot",
      "family": "Claude Sonnet",
      "recommended": true,
      "recommendationReason": "Copilot-hosted Sonnet option for balanced Office work.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gemini-3.1-pro-preview": {
      "provider": "github-copilot",
      "modelId": "gemini-3.1-pro-preview",
      "settingsVisibility": "simple",
      "lab": "GitHub Copilot",
      "family": "Gemini 3.1",
      "recommended": true,
      "recommendationReason": "Copilot-hosted Gemini Pro preview option.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gpt-5.4": {
      "provider": "github-copilot",
      "modelId": "gpt-5.4",
      "settingsVisibility": "simple",
      "lab": "GitHub Copilot",
      "family": "GPT-5.4",
      "recommended": true,
      "recommendationReason": "Best OpenAI-family Copilot slug currently exposed by Pi.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "google": {
    "gemini-3-flash-preview": {
      "provider": "google",
      "modelId": "gemini-3-flash-preview",
      "settingsVisibility": "simple",
      "lab": "Google",
      "family": "Gemini 3",
      "recommended": true,
      "recommendationReason": "Fast Gemini option for lightweight Office tasks.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gemini-3-pro-preview": {
      "provider": "google",
      "modelId": "gemini-3-pro-preview",
      "settingsVisibility": "simple",
      "lab": "Google",
      "family": "Gemini 3",
      "recommended": true,
      "recommendationReason": "Stable Gemini 3 Pro preview fallback.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gemini-3.1-pro-preview": {
      "provider": "google",
      "modelId": "gemini-3.1-pro-preview",
      "settingsVisibility": "simple",
      "lab": "Google",
      "family": "Gemini 3.1",
      "recommended": true,
      "recommendationReason": "Preferred Gemini Pro preview in the refreshed Pi catalog.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "groq": {
    "moonshotai/kimi-k2-instruct": {
      "provider": "groq",
      "modelId": "moonshotai/kimi-k2-instruct",
      "settingsVisibility": "simple",
      "lab": "Groq",
      "family": "Kimi K2",
      "recommended": true,
      "recommendationReason": "Kimi K2 instruct model exposed through Groq.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    },
    "openai/gpt-oss-120b": {
      "provider": "groq",
      "modelId": "openai/gpt-oss-120b",
      "settingsVisibility": "simple",
      "lab": "Groq",
      "family": "GPT OSS",
      "recommended": true,
      "recommendationReason": "Large open-weight model exposed by Groq for fast exploratory tasks.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    }
  },
  "kimi-coding": {
    "k2p6": {
      "provider": "kimi-coding",
      "modelId": "k2p6",
      "settingsVisibility": "advanced",
      "lab": "Moonshot AI",
      "family": "Kimi K2.6",
      "recommended": true,
      "recommendationReason": "Direct Kimi K2.6-compatible alias exposed by Pi; kept Advanced for explicit direct-provider setup.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "kimi-k2-thinking": {
      "provider": "kimi-coding",
      "modelId": "kimi-k2-thinking",
      "settingsVisibility": "advanced",
      "lab": "Moonshot AI",
      "family": "Kimi K2",
      "recommended": true,
      "recommendationReason": "Direct Kimi thinking slug; kept Advanced for explicit direct-provider setup.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "openai": {
    "gpt-4.1": {
      "provider": "openai",
      "modelId": "gpt-4.1",
      "settingsVisibility": "simple",
      "lab": "OpenAI",
      "family": "GPT-4.1",
      "recommended": true,
      "recommendationReason": "Lower-cost legacy-compatible OpenAI option kept visible for existing API users.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gpt-5.4": {
      "provider": "openai",
      "modelId": "gpt-5.4",
      "settingsVisibility": "simple",
      "lab": "OpenAI",
      "family": "GPT-5.4",
      "recommended": true,
      "recommendationReason": "Strong current OpenAI fallback for professional document work.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gpt-5.4-pro": {
      "provider": "openai",
      "modelId": "gpt-5.4-pro",
      "settingsVisibility": "simple",
      "lab": "OpenAI",
      "family": "GPT-5.4",
      "recommended": true,
      "recommendationReason": "Current available Pro-class OpenAI slug while gpt-5.5-pro is not present in Pi.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gpt-5.5": {
      "provider": "openai",
      "modelId": "gpt-5.5",
      "settingsVisibility": "simple",
      "lab": "OpenAI",
      "family": "GPT-5.5",
      "recommended": true,
      "recommendationReason": "Best current OpenAI general-purpose model in the refreshed Pi catalog.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "openai-codex": {
    "gpt-5.3-codex": {
      "provider": "openai-codex",
      "modelId": "gpt-5.3-codex",
      "settingsVisibility": "simple",
      "lab": "OpenAI",
      "family": "Codex",
      "recommended": true,
      "recommendationReason": "Coding-agent oriented model for advanced companion mode once OAuth is implemented.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gpt-5.4": {
      "provider": "openai-codex",
      "modelId": "gpt-5.4",
      "settingsVisibility": "simple",
      "lab": "OpenAI",
      "family": "GPT-5.4",
      "recommended": true,
      "recommendationReason": "Current high-quality companion-owned OAuth fallback.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gpt-5.5": {
      "provider": "openai-codex",
      "modelId": "gpt-5.5",
      "settingsVisibility": "simple",
      "lab": "OpenAI",
      "family": "GPT-5.5",
      "recommended": true,
      "recommendationReason": "Preferred ChatGPT/Codex-family model once companion OAuth token brokerage exists.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "opencode": {
    "claude-opus-4-7": {
      "provider": "opencode",
      "modelId": "claude-opus-4-7",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "Claude Opus",
      "recommended": true,
      "recommendationReason": "OpenCode-hosted Opus default for long-form document editing.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    },
    "gemini-3.1-pro": {
      "provider": "opencode",
      "modelId": "gemini-3.1-pro",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "Gemini 3.1",
      "recommended": true,
      "recommendationReason": "Gemini Pro option through OpenCode.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "glm-5.1": {
      "provider": "opencode",
      "modelId": "glm-5.1",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "GLM-5",
      "recommended": true,
      "recommendationReason": "Current GLM 5.1 slug through OpenCode.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "gpt-5.4": {
      "provider": "opencode",
      "modelId": "gpt-5.4",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "GPT-5.4",
      "recommended": true,
      "recommendationReason": "OpenAI-family fallback through OpenCode.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "kimi-k2.6": {
      "provider": "opencode",
      "modelId": "kimi-k2.6",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "Kimi K2",
      "recommended": true,
      "recommendationReason": "Current Kimi K2.6 slug through OpenCode.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    }
  },
  "opencode-go": {
    "glm-5.1": {
      "provider": "opencode-go",
      "modelId": "glm-5.1",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "GLM-5",
      "recommended": true,
      "recommendationReason": "Current GLM 5.1 option for OpenCode Go.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "kimi-k2.5": {
      "provider": "opencode-go",
      "modelId": "kimi-k2.5",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "Kimi K2",
      "recommended": true,
      "recommendationReason": "Kimi K2.5 fallback for OpenCode Go.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "kimi-k2.6": {
      "provider": "opencode-go",
      "modelId": "kimi-k2.6",
      "settingsVisibility": "simple",
      "lab": "OpenCode",
      "family": "Kimi K2",
      "recommended": true,
      "recommendationReason": "Current Kimi K2.6 default for OpenCode Go.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "openrouter": {
    "deepseek/deepseek-v4-pro": {
      "provider": "openrouter",
      "modelId": "deepseek/deepseek-v4-pro",
      "settingsVisibility": "simple",
      "lab": "OpenRouter",
      "family": "DeepSeek V4",
      "recommended": true,
      "recommendationReason": "Current DeepSeek V4 Pro OpenRouter slug.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "google/gemini-3.1-pro-preview": {
      "provider": "openrouter",
      "modelId": "google/gemini-3.1-pro-preview",
      "settingsVisibility": "simple",
      "lab": "OpenRouter",
      "family": "Gemini 3.1",
      "recommended": true,
      "recommendationReason": "Gemini Pro preview via OpenRouter.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "moonshotai/kimi-k2.6": {
      "provider": "openrouter",
      "modelId": "moonshotai/kimi-k2.6",
      "settingsVisibility": "simple",
      "lab": "OpenRouter",
      "family": "Kimi K2",
      "recommended": true,
      "recommendationReason": "Current Kimi K2.6 OpenRouter slug.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "openai/gpt-5.4": {
      "provider": "openrouter",
      "modelId": "openai/gpt-5.4",
      "settingsVisibility": "simple",
      "lab": "OpenRouter",
      "family": "GPT-5.4",
      "recommended": true,
      "recommendationReason": "Best OpenAI-family model exposed by OpenRouter in the refreshed Pi catalog.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    },
    "x-ai/grok-4.20": {
      "provider": "openrouter",
      "modelId": "x-ai/grok-4.20",
      "settingsVisibility": "simple",
      "lab": "OpenRouter",
      "family": "Grok 4.20",
      "recommended": true,
      "recommendationReason": "Current Grok 4.20 OpenRouter slug.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    }
  },
  "vercel-ai-gateway": {
    "google/gemini-3.1-pro-preview": {
      "provider": "vercel-ai-gateway",
      "modelId": "google/gemini-3.1-pro-preview",
      "settingsVisibility": "simple",
      "lab": "Vercel",
      "family": "Gemini 3.1",
      "recommended": true,
      "recommendationReason": "Gemini Pro preview via Vercel AI Gateway.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "moonshotai/kimi-k2.6": {
      "provider": "vercel-ai-gateway",
      "modelId": "moonshotai/kimi-k2.6",
      "settingsVisibility": "simple",
      "lab": "Vercel",
      "family": "Kimi K2",
      "recommended": true,
      "recommendationReason": "Current Kimi K2.6 Vercel Gateway slug.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "openai/gpt-5.4": {
      "provider": "vercel-ai-gateway",
      "modelId": "openai/gpt-5.4",
      "settingsVisibility": "simple",
      "lab": "Vercel",
      "family": "GPT-5.4",
      "recommended": true,
      "recommendationReason": "Best OpenAI-family model exposed by Vercel AI Gateway in the refreshed Pi catalog.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    },
    "xai/grok-4.20-reasoning": {
      "provider": "vercel-ai-gateway",
      "modelId": "xai/grok-4.20-reasoning",
      "settingsVisibility": "simple",
      "lab": "Vercel",
      "family": "Grok 4.20",
      "recommended": true,
      "recommendationReason": "Reasoning Grok 4.20 Vercel Gateway slug.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "zai/glm-5.1": {
      "provider": "vercel-ai-gateway",
      "modelId": "zai/glm-5.1",
      "settingsVisibility": "simple",
      "lab": "Vercel",
      "family": "GLM-5",
      "recommended": true,
      "recommendationReason": "Current GLM 5.1 Vercel Gateway slug.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    }
  },
  "xai": {
    "grok-4.20-0309-non-reasoning": {
      "provider": "xai",
      "modelId": "grok-4.20-0309-non-reasoning",
      "settingsVisibility": "simple",
      "lab": "xAI",
      "family": "Grok 4.20",
      "recommended": true,
      "recommendationReason": "Lower-latency Grok 4.20-compatible direct xAI slug.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "grok-4.20-0309-reasoning": {
      "provider": "xai",
      "modelId": "grok-4.20-0309-reasoning",
      "settingsVisibility": "simple",
      "lab": "xAI",
      "family": "Grok 4.20",
      "recommended": true,
      "recommendationReason": "Current reasoning Grok 4.20-compatible direct xAI slug in Pi.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  },
  "zai": {
    "glm-5": {
      "provider": "zai",
      "modelId": "glm-5",
      "settingsVisibility": "advanced",
      "lab": "Z.AI",
      "family": "GLM-5",
      "recommended": true,
      "recommendationReason": "Direct GLM 5 fallback; kept Advanced for explicit opt-in.",
      "defaultForProvider": false,
      "requiresUnrecommendedWarning": false
    },
    "glm-5.1": {
      "provider": "zai",
      "modelId": "glm-5.1",
      "settingsVisibility": "advanced",
      "lab": "Z.AI",
      "family": "GLM-5",
      "recommended": true,
      "recommendationReason": "Direct GLM 5.1 slug; kept Advanced because direct regional-provider setup should be intentional.",
      "defaultForProvider": true,
      "requiresUnrecommendedWarning": false
    }
  }
} as const satisfies Record<string, Record<string, ProviderModelPreference>>;

export const DEFAULT_ENABLED_MODELS_BY_PROVIDER = {
  "anthropic": [
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-sonnet-4-6"
  ],
  "google": [
    "gemini-3.1-pro-preview",
    "gemini-3-pro-preview",
    "gemini-3-flash-preview"
  ],
  "openai": [
    "gpt-5.5",
    "gpt-5.4-pro",
    "gpt-5.4",
    "gpt-4.1"
  ]
} as const satisfies Record<string, readonly string[]>;

export const SIMPLE_RECOMMENDED_MODELS_BY_PROVIDER = {
  "anthropic": [
    "claude-opus-4-7",
    "claude-opus-4-6",
    "claude-sonnet-4-6"
  ],
  "github-copilot": [
    "gpt-5.4",
    "claude-opus-4.6",
    "claude-sonnet-4.6",
    "gemini-3.1-pro-preview"
  ],
  "google": [
    "gemini-3.1-pro-preview",
    "gemini-3-pro-preview",
    "gemini-3-flash-preview"
  ],
  "groq": [
    "moonshotai/kimi-k2-instruct",
    "openai/gpt-oss-120b"
  ],
  "openai": [
    "gpt-5.5",
    "gpt-5.4-pro",
    "gpt-5.4",
    "gpt-4.1"
  ],
  "openai-codex": [
    "gpt-5.5",
    "gpt-5.4",
    "gpt-5.3-codex"
  ],
  "opencode": [
    "claude-opus-4-7",
    "gpt-5.4",
    "gemini-3.1-pro",
    "kimi-k2.6",
    "glm-5.1"
  ],
  "opencode-go": [
    "kimi-k2.6",
    "kimi-k2.5",
    "glm-5.1"
  ],
  "openrouter": [
    "openai/gpt-5.4",
    "google/gemini-3.1-pro-preview",
    "x-ai/grok-4.20",
    "moonshotai/kimi-k2.6",
    "deepseek/deepseek-v4-pro"
  ],
  "vercel-ai-gateway": [
    "openai/gpt-5.4",
    "google/gemini-3.1-pro-preview",
    "xai/grok-4.20-reasoning",
    "moonshotai/kimi-k2.6",
    "zai/glm-5.1"
  ],
  "xai": [
    "grok-4.20-0309-reasoning",
    "grok-4.20-0309-non-reasoning"
  ]
} as const satisfies Record<string, readonly string[]>;

export const SIMPLE_VISIBLE_PROVIDERS = [
  "anthropic",
  "github-copilot",
  "google",
  "groq",
  "openai",
  "openai-codex",
  "opencode",
  "opencode-go",
  "openrouter",
  "vercel-ai-gateway",
  "xai"
] as const satisfies readonly string[];

const PROVIDER_SETTINGS_LOOKUP = PROVIDER_SETTINGS_PREFERENCES as Record<string, ProviderSettingsPreference>;
const PROVIDER_MODEL_LOOKUP = PROVIDER_MODEL_PREFERENCES as Record<string, Record<string, ProviderModelPreference>>;

export function getProviderSettingsPreference(provider: string): ProviderSettingsPreference {
  return PROVIDER_SETTINGS_LOOKUP[provider] ?? {
    provider,
    label: provider,
    lab: provider,
    settingsVisibility: "advanced",
    defaultEnabled: false,
  };
}

export function getProviderModelPreference(provider: string, modelId: string): ProviderModelPreference | undefined {
  return PROVIDER_MODEL_LOOKUP[provider]?.[modelId];
}

export function getProviderDefaultModel(provider: string): string | undefined {
  return getProviderSettingsPreference(provider).defaultModel;
}

export function isSimpleVisibleProvider(provider: string): boolean {
  return getProviderSettingsPreference(provider).settingsVisibility === "simple";
}
