import { Type } from "@sinclair/typebox";
import type { OfficeToolDefinition } from "./types";

export const EXCEL_OFFICE_TOOL_DEFINITIONS: readonly OfficeToolDefinition[] = [
  {
    name: "get_cell_ranges",
    hosts: ["excel"],
    category: "read",
    label: "Get Cell Ranges",
    description: "Excel-only first-class range read tool for cell/range values, text, formulas, and number formats.",
    parameters: Type.Object({
      sheetName: Type.Optional(Type.String({ description: "Worksheet name that contains the range. Defaults to the active worksheet." })),
      address: Type.Optional(Type.String({ description: "A1-style cell/range address. Defaults to the current selection." })),
      includeValues: Type.Optional(Type.Boolean({ description: "Include range values in the response. Defaults to true." })),
      includeText: Type.Optional(Type.Boolean({ description: "Include rendered text values in the response. Defaults to true." })),
      includeFormulas: Type.Optional(Type.Boolean({ description: "Include range formulas in the response. Defaults to true." })),
      includeNumberFormat: Type.Optional(Type.Boolean({ description: "Include number formats in the response. Defaults to true." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "set_cell_range",
    hosts: ["excel"],
    category: "write-doc",
    label: "Set Cell Range",
    description: "Excel-only first-class range write tool for setting values in a target cell/range.",
    parameters: Type.Object({
      sheetName: Type.Optional(Type.String({ description: "Worksheet name that contains the destination range. Defaults to active worksheet." })),
      address: Type.Optional(Type.String({ description: "A1-style destination address. Defaults to current selection." })),
      values: Type.Optional(Type.Any({ description: "2D matrix values to write into the target range." })),
      content: Type.Optional(Type.String({ description: "JSON matrix alias when values is omitted." })),
      options: Type.Optional(Type.Any({ description: "Additional write options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "clear_cell_range",
    hosts: ["excel"],
    category: "write-doc",
    label: "Clear Cell Range",
    description: "Excel-only first-class range clear tool. Destructive clears should set confirmDestructive=true.",
    parameters: Type.Object({
      sheetName: Type.Optional(Type.String({ description: "Worksheet name that contains the range to clear." })),
      address: Type.Optional(Type.String({ description: "A1-style address to clear. Defaults to current selection." })),
      applyTo: Type.Optional(Type.String({ description: "Clear scope: contents, formats, hyperlinks, removeHyperlinks, or all." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Required by policy for destructive all/contents clears when applicable." })),
      options: Type.Optional(Type.Any({ description: "Additional clear options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "resize_range",
    hosts: ["excel"],
    category: "write-doc",
    label: "Resize Range",
    description: "Excel-only first-class range layout tool for computing/activating resized ranges by count or delta.",
    parameters: Type.Object({
      sheetName: Type.Optional(Type.String({ description: "Worksheet name that contains the source range." })),
      address: Type.Optional(Type.String({ description: "A1-style source range address. Defaults to current selection." })),
      rowCount: Type.Optional(Type.Number({ minimum: 1, description: "Final row count for the resized range." })),
      columnCount: Type.Optional(Type.Number({ minimum: 1, description: "Final column count for the resized range." })),
      rowDelta: Type.Optional(Type.Number({ description: "Relative row delta when rowCount is not provided." })),
      columnDelta: Type.Optional(Type.Number({ description: "Relative column delta when columnCount is not provided." })),
      activate: Type.Optional(Type.Boolean({ description: "Activate/select the resized range after resolving it." })),
      options: Type.Optional(Type.Any({ description: "Additional resize options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "copy_to",
    hosts: ["excel"],
    category: "write-doc",
    label: "Copy To Range",
    description: "Excel-only first-class range copy tool that copies a source range into a destination range.",
    parameters: Type.Object({
      sourceSheetName: Type.Optional(Type.String({ description: "Worksheet name for the source range. Defaults to active worksheet." })),
      sourceAddress: Type.Optional(Type.String({ description: "A1-style source range address. Defaults to current selection." })),
      destinationSheetName: Type.Optional(Type.String({ description: "Worksheet name for the destination range." })),
      destinationAddress: Type.String({ description: "A1-style destination range address." }),
      copyType: Type.Optional(Type.String({ description: "Excel copy type: All, Formats, Formulas, Values, or Link." })),
      skipBlanks: Type.Optional(Type.Boolean({ description: "Skip blank cells while copying. Defaults to false." })),
      transpose: Type.Optional(Type.Boolean({ description: "Transpose copied rows/columns. Defaults to false." })),
      options: Type.Optional(Type.Any({ description: "Additional copy options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "modify_sheet_structure",
    hosts: ["excel"],
    category: "write-doc",
    label: "Modify Sheet Structure",
    description: "Excel-only first-class worksheet structure tool for create, rename, duplicate, and delete operations.",
    parameters: Type.Object({
      operation: Type.String({ description: "Worksheet operation (create_worksheet, rename_worksheet, duplicate_worksheet, delete_worksheet, set_gridlines, set_headings, set_print_area)." }),
      sheetName: Type.Optional(Type.String({ description: "Worksheet name targeted by rename/duplicate/delete operations." })),
      name: Type.Optional(Type.String({ description: "Worksheet name for create/rename/duplicate operations." })),
      relativeTo: Type.Optional(Type.String({ description: "Worksheet name used as placement anchor for duplication." })),
      positionType: Type.Optional(Type.String({ description: "Worksheet copy placement type when duplicating (before/after)." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Required by policy for destructive worksheet operations when applicable." })),
      options: Type.Optional(Type.Any({ description: "Additional structure options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "modify_object",
    hosts: ["excel"],
    category: "write-doc",
    label: "Modify Excel Object",
    description: "Excel-only first-class object mutation tool for table/chart/pivot/worksheet object operations through native workbook actions.",
    parameters: Type.Object({
      operation: Type.String({
        description:
          "Excel object mutation operation (format_range, create_table, format_table, apply_table_filter, clear_table_filter, clear_table_filters, reapply_table_filters, create_chart, update_chart, create_pivot_table, update_pivot_table, sort_pivot_field, sort_pivot_by_labels, sort_pivot_by_values, refresh_pivot_table, set_worksheet_gridlines, set_worksheet_headings, set_print_area, set_data_validation, clear_data_validation, add_conditional_format, clear_conditional_formats, insert_inline_picture).",
      }),
      sheetName: Type.Optional(Type.String({ description: "Worksheet name for range/table/chart/pivot operations." })),
      address: Type.Optional(Type.String({ description: "A1-style range address when an operation targets a worksheet range." })),
      tableName: Type.Optional(Type.String({ description: "Target table name for table-oriented operations." })),
      chartName: Type.Optional(Type.String({ description: "Target chart name for chart-oriented operations." })),
      pivotTableName: Type.Optional(Type.String({ description: "Target PivotTable name for pivot-oriented operations." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Set true for destructive operations when required." })),
      options: Type.Optional(Type.Any({ description: "Additional object-operation options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "get_all_objects",
    hosts: ["excel"],
    category: "read",
    label: "Get Excel Objects",
    description: "Excel-only first-class object inventory read for workbook/worksheet tables, charts, PivotTables, and named items.",
    parameters: Type.Object({
      scope: Type.Optional(Type.String({ description: "Object inventory scope: workbook, worksheet, selection, or active." })),
      includeFormatting: Type.Optional(Type.Boolean({ description: "Include formatting metadata when available. Defaults to true." })),
      objectTypes: Type.Optional(Type.Array(Type.String(), { description: "Optional object kinds to include: table, chart, pivotTable, namedItem, worksheet, cell." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "search_data",
    hosts: ["excel"],
    category: "read",
    label: "Search Excel Data",
    description: "Excel-only first-class workbook/worksheet data search across tables, charts, PivotTables, named items, and cited cells.",
    parameters: Type.Object({
      query: Type.String({ description: "Case-insensitive query used to search workbook/worksheet objects and cited cells." }),
      scope: Type.Optional(Type.String({ description: "Search scope: workbook, worksheet, selection, or active." })),
      objectTypes: Type.Optional(Type.Array(Type.String(), { description: "Optional object kinds to search: table, chart, pivotTable, namedItem, worksheet, cell." })),
      limit: Type.Optional(Type.Number({ minimum: 1, maximum: 200, description: "Maximum number of matches to return." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "get_range_as_csv",
    hosts: ["excel"],
    category: "read",
    label: "Export Range as CSV",
    description: "Excel-only first-class CSV export for auditable range snapshots. Use includeFormulas=true when formula-first verification is required.",
    parameters: Type.Object({
      sheetName: Type.Optional(Type.String({ description: "Worksheet name that contains the source range. Defaults to active worksheet." })),
      address: Type.Optional(Type.String({ description: "A1-style source range address. Defaults to current selection." })),
      delimiter: Type.Optional(Type.String({ description: "CSV delimiter. Defaults to comma." })),
      quoteValues: Type.Optional(Type.Boolean({ description: "Wrap and escape all CSV cells in quotes. Defaults to false." })),
      includeHeaders: Type.Optional(Type.Boolean({ description: "Include header row. Defaults to true." })),
      includeFormulas: Type.Optional(Type.Boolean({ description: "Export formulas instead of rendered values when available. Defaults to false." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "read_range_image",
    hosts: ["excel"],
    category: "read",
    label: "Read Range Image",
    description: "Excel-only first-class range imagery read for visual verification workflows on the active worksheet selection/range.",
    parameters: Type.Object({
      sheetName: Type.Optional(Type.String({ description: "Worksheet name hint for the range image capture context." })),
      address: Type.Optional(Type.String({ description: "A1-style range address hint for the range image capture context." })),
      scope: Type.Optional(Type.String({ description: "Range visual scope. Currently expects the active selection." })),
      includeFormatting: Type.Optional(Type.Boolean({ description: "Include formatting metadata in the visual payload. Defaults to true." })),
      maxImages: Type.Optional(Type.Number({ minimum: 1, maximum: 4, description: "Maximum number of range images to include." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "extract_chart_xml",
    hosts: ["excel"],
    category: "read",
    label: "Extract Chart XML",
    description: "Excel-only first-class chart XML extraction that returns a runtime-generated chart metadata XML snapshot (not full package OOXML).",
    parameters: Type.Object({
      sheetName: Type.Optional(Type.String({ description: "Worksheet name that contains the chart. Defaults to active worksheet." })),
      chartName: Type.Optional(Type.String({ description: "Chart name to extract. Required when chartId/chartIndex are not provided." })),
      chartId: Type.Optional(Type.String({ description: "Optional chart id alias when chartName is unknown." })),
      chartIndex: Type.Optional(Type.Number({ minimum: 1, description: "Optional one-based chart index when chartName is unknown." })),
    }),
    executor: "office-bridge",
  },
];
