import { Type } from "@sinclair/typebox";
import type { OfficeToolDefinition } from "./types";

export const POWERPOINT_OFFICE_TOOL_DEFINITIONS: readonly OfficeToolDefinition[] = [
  {
    name: "get_presentation_structure",
    hosts: ["powerpoint"],
    category: "read",
    capabilityId: "powerpoint.presentation.structure",
    riskLevel: "low",
    keywords: ["powerpoint", "presentation", "outline", "slides", "structure", "sections"],
    label: "Read Presentation Structure",
    description: "PowerPoint-only first-class presentation structure read. Returns slide order plus layout/master structure metadata and bounded slide previews.",
    parameters: Type.Object({
      maxSlides: Type.Optional(Type.Number({ minimum: 1, description: "Maximum number of slides to include in the structural preview." })),
      includeSlideText: Type.Optional(Type.Boolean({ description: "Include bounded slide text previews. Defaults to true." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "get_slide",
    hosts: ["powerpoint"],
    category: "read",
    capabilityId: "powerpoint.slide.read",
    riskLevel: "low",
    keywords: ["powerpoint", "slide", "read", "notes", "shapes", "content"],
    label: "Read Slide",
    description: "PowerPoint-only first-class per-slide read. Resolve a slide by slideId/slideIndex (or selection) and return structured slide details.",
    parameters: Type.Object({
      slideId: Type.Optional(Type.String({ description: "PowerPoint slide ID to read." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index to read." })),
      includeShapes: Type.Optional(Type.Boolean({ description: "Include shape summaries for the resolved slide. Defaults to true." })),
      includeSlideText: Type.Optional(Type.Boolean({ description: "Include title/body text previews for the resolved slide. Defaults to true." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "list_slide_shapes",
    hosts: ["powerpoint"],
    category: "read",
    capabilityId: "powerpoint.shapes.inventory",
    riskLevel: "low",
    keywords: ["powerpoint", "shape", "inventory", "text box", "image", "chart"],
    label: "List Slide Shapes",
    description: "PowerPoint-only first-class shape inventory read. Returns structured shape summaries for the resolved slide.",
    parameters: Type.Object({
      slideId: Type.Optional(Type.String({ description: "PowerPoint slide ID whose shapes should be listed." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index whose shapes should be listed." })),
      maxShapes: Type.Optional(Type.Number({ minimum: 1, description: "Optional maximum number of shapes to return." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "modify_presentation_structure",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.presentation.structure.write",
    riskLevel: "high",
    keywords: ["powerpoint", "slides", "section", "move", "delete", "structure", "layout"],
    label: "Modify Presentation Structure",
    description: "PowerPoint-only first-class structure mutation tool for slide create/move/reorder/delete/layout operations through native host actions.",
    parameters: Type.Object({
      operation: Type.String({ description: "PowerPoint structure operation (create_slide, delete_slide, reorder_slides, apply_layout, create_agenda_slide, create_section_divider, create_summary_slide)." }),
      slideId: Type.Optional(Type.String({ description: "Target slide ID for the operation." })),
      slideIds: Type.Optional(Type.Array(Type.String(), { description: "Ordered list of slide IDs for multi-slide operations." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index target." })),
      targetSlideId: Type.Optional(Type.String({ description: "Insertion target slide ID where applicable." })),
      formatting: Type.Optional(Type.String({ description: "PowerPoint insert formatting mode when supported." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Required by policy for destructive operations when applicable." })),
      content: Type.Optional(Type.String({ description: "Optional text payload used by supported slide-creation helpers." })),
      options: Type.Optional(Type.Any({ description: "Additional operation-specific options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "duplicate_slide",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.slide.duplicate",
    riskLevel: "medium",
    keywords: ["powerpoint", "duplicate", "copy", "slide"],
    label: "Duplicate Slide",
    description: "PowerPoint-only first-class slide duplication tool supporting one or multiple source slides and optional insertion target/formatting controls.",
    parameters: Type.Object({
      slideId: Type.Optional(Type.String({ description: "Single source slide ID to duplicate." })),
      slideIds: Type.Optional(Type.Array(Type.String(), { description: "One or more source slide IDs to duplicate in order." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based source slide index when slideId is not known." })),
      targetSlideId: Type.Optional(Type.String({ description: "Slide ID to insert duplicates after." })),
      formatting: Type.Optional(Type.String({ description: "PowerPoint insert formatting mode when supported." })),
      options: Type.Optional(Type.Any({ description: "Additional duplication options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "insert_slide_element",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.slide.element.insert",
    riskLevel: "medium",
    keywords: ["powerpoint", "insert", "shape", "text box", "image", "table", "element"],
    label: "Insert Slide Element",
    description: "PowerPoint-only first-class element insertion tool for explicit shape/table/diagram/picture authoring through native actions.",
    parameters: Type.Object({
      operation: Type.String({ description: "PowerPoint element insertion operation (add_text_box, add_geometric_shape, add_table, add_line, add_process_flow, add_simple_diagram, insert_inline_picture)." }),
      slideId: Type.Optional(Type.String({ description: "Target slide ID for inserting the new element." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index target when slideId is not known." })),
      shapeId: Type.Optional(Type.String({ description: "Optional shape target for grouped operations." })),
      content: Type.Optional(Type.String({ description: "Primary text payload (or base64 image payload for insert_inline_picture)." })),
      text: Type.Optional(Type.String({ description: "Alias for content when inserting text." })),
      values: Type.Optional(Type.Any({ description: "Matrix payload for table insertion when applicable." })),
      options: Type.Optional(Type.Any({ description: "Additional insertion options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "remove_slide_element",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.slide.element.remove",
    riskLevel: "high",
    keywords: ["powerpoint", "remove", "delete", "shape", "element"],
    label: "Remove Slide Element",
    description: "PowerPoint-only first-class element removal tool for explicit shape/text removal operations with destructive-action policy support.",
    parameters: Type.Object({
      operation: Type.String({ description: "PowerPoint element removal operation (remove_shape, remove_shapes, clear_shape_text)." }),
      slideId: Type.Optional(Type.String({ description: "Target slide ID for the removal operation." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index target when slideId is not known." })),
      shapeId: Type.Optional(Type.String({ description: "Primary shape ID to remove or clear." })),
      shapeIds: Type.Optional(Type.Array(Type.String(), { description: "One or more shape IDs for multi-shape removal." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Required by policy for destructive operations when applicable." })),
      options: Type.Optional(Type.Any({ description: "Additional removal options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "edit_slide_text",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.text.edit",
    riskLevel: "medium",
    keywords: ["powerpoint", "text", "shape", "edit", "speaker notes"],
    label: "Edit Slide Text",
    description: "PowerPoint-only first-class text editing for slide shapes/selection. Use this instead of generic office_apply_edit when the intent is text-focused slide authoring.",
    parameters: Type.Object({
      operation: Type.Optional(Type.String({ description: "PowerPoint text-edit operation (set_shape_text, append_shape_text, clear_shape_text, insert_text). Defaults to set_shape_text when shapeId is provided, otherwise insert_text." })),
      slideId: Type.Optional(Type.String({ description: "Target slide ID for text updates." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index target when slideId is not known." })),
      shapeId: Type.Optional(Type.String({ description: "Shape ID whose text should be updated." })),
      content: Type.Optional(Type.String({ description: "Text payload to apply." })),
      text: Type.Optional(Type.String({ description: "Alias for content." })),
      placement: Type.Optional(Type.String({ description: "Optional placement hint (replace or after)." })),
      options: Type.Optional(Type.Any({ description: "Additional text-edit options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "edit_slide_xml",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.ooxml.edit",
    riskLevel: "high",
    keywords: ["powerpoint", "xml", "ooxml", "package", "advanced", "serialized"],
    label: "Edit Slide XML",
    description: "PowerPoint-only first-class serialized/XML editing tool for slide notes and package-level OOXML workflows, including base64 import/export paths.",
    parameters: Type.Object({
      operation: Type.String({ description: "PowerPoint XML/serialized operation (inspect_presentation_package, get_presentation_theme, get_slide_notes, set_slide_notes, replace_slide_notes, import_slides_from_base64, merge_presentation_from_base64, export_slides_as_base64)." }),
      slideId: Type.Optional(Type.String({ description: "Target slide ID for slide-scoped XML operations." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index target when slideId is not known." })),
      content: Type.Optional(Type.String({ description: "Text or base64 payload used by mutating XML operations." })),
      base64: Type.Optional(Type.String({ description: "Alias for content when providing serialized PPTX payloads." })),
      formatting: Type.Optional(Type.String({ description: "Insert formatting mode for base64 import operations when supported." })),
      options: Type.Optional(Type.Any({ description: "Additional XML operation options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "edit_slide_master",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.layout.apply",
    riskLevel: "medium",
    keywords: ["powerpoint", "layout", "master", "apply", "slide"],
    label: "Apply Slide Layout",
    description: "PowerPoint-only legacy-named tool for applying an existing slide layout. It does not mutate slide masters or layout definitions.",
    parameters: Type.Object({
      operation: Type.Optional(Type.String({ description: "PowerPoint layout operation. Currently supports apply_layout/set_layout only; this legacy-named tool does not edit slide masters." })),
      slideId: Type.Optional(Type.String({ description: "Target slide ID whose layout should be updated." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index target when slideId is not known." })),
      layoutId: Type.Optional(Type.String({ description: "Layout ID to apply." })),
      layoutName: Type.Optional(Type.String({ description: "Layout name to apply." })),
      slideMasterId: Type.Optional(Type.String({ description: "Optional slide master ID used only to resolve the requested layout." })),
      slideMasterName: Type.Optional(Type.String({ description: "Optional slide master name used only to resolve the requested layout." })),
      options: Type.Optional(Type.Any({ description: "Additional layout-application options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "edit_slide_chart",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.chart.edit",
    riskLevel: "medium",
    keywords: ["powerpoint", "chart", "data", "series", "ooxml", "edit"],
    label: "Edit Slide Chart",
    description: "PowerPoint-only first-class chart workflow tool for chart inspection and serialized chart create/update paths.",
    parameters: Type.Object({
      operation: Type.Optional(Type.String({ description: "PowerPoint chart operation (get_slide_charts, add_slide_chart, update_slide_chart). Defaults to update_slide_chart when omitted." })),
      slideId: Type.Optional(Type.String({ description: "Target slide ID for chart inspection or mutation." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based slide index target when slideId is not known." })),
      shapeId: Type.Optional(Type.String({ description: "Optional chart shape ID for precise chart targeting." })),
      chartIndex: Type.Optional(Type.Number({ minimum: 1, description: "Optional one-based chart index within the target slide package." })),
      shapeName: Type.Optional(Type.String({ description: "Optional chart shape name used to resolve chart edits." })),
      title: Type.Optional(Type.String({ description: "Chart title for create/update operations." })),
      categories: Type.Optional(Type.Any({ description: "Ordered category labels for chart create/update operations." })),
      series: Type.Optional(Type.Any({ description: "Series payload for chart create/update operations." })),
      replaceOriginal: Type.Optional(Type.Boolean({ description: "When true (default), replace the source slide after serialized chart updates." })),
      formatting: Type.Optional(Type.String({ description: "Insert formatting mode when serialized chart updates insert replacement slides." })),
      options: Type.Optional(Type.Any({ description: "Additional chart operation options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "copy_image_between_slides",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.image.copy",
    riskLevel: "medium",
    keywords: ["powerpoint", "image", "copy", "between slides", "picture"],
    label: "Copy Image Between Slides",
    description: "PowerPoint-only first-class media workflow tool that copies an image from a source slide/shape to a destination slide or shape.",
    parameters: Type.Object({
      sourceSlideId: Type.Optional(Type.String({ description: "Source slide ID that contains the image shape to copy." })),
      sourceSlideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based source slide index when sourceSlideId is unknown." })),
      sourceShapeId: Type.Optional(Type.String({ description: "Source image shape ID to copy from." })),
      sourceImageBase64: Type.Optional(Type.String({ description: "Optional image base64 override when source shape export is unavailable." })),
      targetSlideId: Type.Optional(Type.String({ description: "Destination slide ID for image placement/replacement." })),
      targetSlideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based destination slide index when targetSlideId is unknown." })),
      targetShapeId: Type.Optional(Type.String({ description: "Destination shape ID to update. If omitted, inserts a new image shape." })),
      left: Type.Optional(Type.Number({ description: "Optional destination left position in points for inserted images." })),
      top: Type.Optional(Type.Number({ description: "Optional destination top position in points for inserted images." })),
      width: Type.Optional(Type.Number({ description: "Optional destination width in points for inserted images." })),
      height: Type.Optional(Type.Number({ description: "Optional destination height in points for inserted images." })),
      options: Type.Optional(Type.Any({ description: "Additional media-copy options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "search_icons",
    hosts: ["powerpoint"],
    category: "read",
    capabilityId: "powerpoint.icons.search",
    riskLevel: "low",
    keywords: ["powerpoint", "icons", "search", "catalog", "visual"],
    label: "Search Slide Icons",
    description: "PowerPoint-only first-class icon search. Returns icon matches from the supported SVG-backed runtime icon catalog without mutating slides.",
    parameters: Type.Object({
      query: Type.String({ description: "Icon search query text." }),
      maxResults: Type.Optional(Type.Number({ minimum: 1, maximum: 50, description: "Maximum number of icon matches to return." })),
      style: Type.Optional(Type.String({ description: "Optional style/category hint used by the icon catalog search." })),
      options: Type.Optional(Type.Any({ description: "Additional icon-search options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "insert_icon",
    hosts: ["powerpoint"],
    category: "write-doc",
    capabilityId: "powerpoint.icons.insert",
    riskLevel: "medium",
    keywords: ["powerpoint", "icons", "insert", "visual", "symbol"],
    label: "Insert Slide Icon",
    description: "PowerPoint-only first-class icon insertion tool that inserts or updates an SVG-rasterized icon image shape on the target slide where supported.",
    parameters: Type.Object({
      iconId: Type.Optional(Type.String({ description: "Icon ID returned by search_icons." })),
      iconName: Type.Optional(Type.String({ description: "Icon name alias when iconId is unknown." })),
      query: Type.Optional(Type.String({ description: "Fallback query used when selecting an icon by search text." })),
      slideId: Type.Optional(Type.String({ description: "Target slide ID for icon insertion." })),
      slideIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based target slide index when slideId is unknown." })),
      shapeId: Type.Optional(Type.String({ description: "Optional target shape ID for icon replacement workflows." })),
      left: Type.Optional(Type.Number({ description: "Optional icon left position in points." })),
      top: Type.Optional(Type.Number({ description: "Optional icon top position in points." })),
      width: Type.Optional(Type.Number({ description: "Optional icon width in points." })),
      height: Type.Optional(Type.Number({ description: "Optional icon height in points." })),
      fillColor: Type.Optional(Type.String({ description: "Optional icon fill/text color (hex/rgb)." })),
      lineColor: Type.Optional(Type.String({ description: "Optional icon outline color (hex/rgb)." })),
      options: Type.Optional(Type.Any({ description: "Additional icon insertion options forwarded to the host adapter." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "verify_slides",
    hosts: ["powerpoint"],
    category: "read",
    capabilityId: "powerpoint.presentation.verify",
    riskLevel: "low",
    keywords: ["powerpoint", "verify", "presentation", "slides", "quality", "structure"],
    label: "Verify Slides",
    description: "PowerPoint-only first-class structural verification. Returns a non-mutating summary/details payload for slide/layout/master checks.",
    parameters: Type.Object({
      scope: Type.Optional(Type.String({ description: "Structural verification scope for PowerPoint slides (presentation or selection). Defaults to presentation structure." })),
      maxSlides: Type.Optional(Type.Number({ minimum: 1, description: "Maximum number of slide previews to include in verification details." })),
      includeSlideText: Type.Optional(Type.Boolean({ description: "Include bounded slide text previews in structural verification output." })),
      includeFormatting: Type.Optional(Type.Boolean({ description: "Include layout/master metadata where supported. Defaults to true." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "verify_slide_visual",
    hosts: ["powerpoint"],
    category: "read",
    capabilityId: "powerpoint.slide.visual.verify",
    riskLevel: "low",
    keywords: ["powerpoint", "verify", "visual", "slide image", "snapshot"],
    label: "Verify Slide Visual",
    description: "PowerPoint-only first-class visual verification using supported Office.js slide/shape snapshot paths (not slideshow-frame capture).",
    parameters: Type.Object({
      scope: Type.Optional(Type.String({ description: "Visual verification scope for PowerPoint (selection, slide, or presentation)." })),
      includeFormatting: Type.Optional(Type.Boolean({ description: "Include slide/shape formatting metadata in visual verification details. Defaults to true." })),
      maxImages: Type.Optional(Type.Number({ minimum: 1, maximum: 4, description: "Maximum number of slide/shape snapshot images to include." })),
    }),
    executor: "office-bridge",
  },
];
