import { Type } from "@sinclair/typebox";
import { OFFICE_PROPOSE_EDITS_SEARCH_TEXT_MAX_LENGTH } from "@pi-office/pi-office-pack/protocol";
import type { OfficeToolDefinition } from "./types";

const proposeEditsParams = Type.Object({
  edits: Type.Array(
    Type.Object({
      kind: Type.String({ description: "insert, replace, or delete." }),
      searchText: Type.Optional(Type.String({
        maxLength: OFFICE_PROPOSE_EDITS_SEARCH_TEXT_MAX_LENGTH,
        description: `Existing text to find. Must be <= ${OFFICE_PROPOSE_EDITS_SEARCH_TEXT_MAX_LENGTH} characters; split large rewrites into smaller edits.`,
      })),
      oldText: Type.Optional(Type.String({ description: "Expected existing text (for replace/delete verification)." })),
      newText: Type.Optional(Type.String({ description: "Replacement text (for insert/replace)." })),
      anchor: Type.Optional(Type.String({ description: "Heading or paragraph label to scope the search." })),
      paragraphId: Type.Optional(Type.String({ description: "Paragraph unique ID for precise targeting." })),
      explanation: Type.Optional(Type.String({ description: "Brief rationale for this edit." })),
    }),
    { description: "Ordered list of proposed edits." },
  ),
  summary: Type.String({ description: "One-sentence summary of all proposed changes." }),
});

export const WORD_OFFICE_TOOL_DEFINITIONS: readonly OfficeToolDefinition[] = [
  {
    name: "word_search",
    hosts: ["word"],
    category: "read",
    label: "Search Word Anchors",
    description:
      "Search the active Word document and return deterministic anchors across paragraphs, headings, comments, revisions, fields, content controls, footnotes, and endnotes.",
    discovery: {
      tier: "core",
      capabilityIds: ["word.search", "word.anchors", "word.index"],
      keywords: ["word", "search", "anchor", "index", "paragraph", "heading", "comment", "field", "note"],
      summary: "Find Word passages and structural objects before navigating or editing.",
      riskLevel: "low",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
      fallback: "Use office_get_context or office_read_section if a host cannot run search APIs.",
    },
    parameters: Type.Object({
      query: Type.String({ description: "Text or structural term to search for." }),
      objectTypes: Type.Optional(Type.Array(Type.String(), { description: "Optional object types: text, heading, paragraph, comment, revision, field, contentControl, footnote, endnote." })),
      maxResults: Type.Optional(Type.Number({ minimum: 1, maximum: 50, description: "Maximum results to return. Defaults to 12." })),
      includeContext: Type.Optional(Type.Boolean({ description: "Include surrounding context previews. Defaults to true." })),
      matchCase: Type.Optional(Type.Boolean({ description: "Use case-sensitive text search for native text matches. Defaults to false." })),
      matchWholeWord: Type.Optional(Type.Boolean({ description: "Use whole-word native text search where supported. Defaults to false." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_format_text",
    hosts: ["word"],
    category: "write-doc",
    label: "Format Word Text",
    description:
      "Apply structured Word style, paragraph, font, highlight, or clear-formatting operations to the selection or a precise Word anchor.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.formatting", "word.styles", "word.paragraph"],
      keywords: ["word", "format", "style", "paragraph", "font", "spacing", "indent", "alignment", "highlight"],
      summary: "Format Word paragraphs and ranges without raw Office.js.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
      fallback: "Use reviewable text proposals when formatting support is unavailable or a broad rewrite is needed.",
    },
    parameters: Type.Object({
      target: Type.Optional(Type.Any({ description: "Selection, paragraph, heading, contentControl, field, or searchResult anchor. Defaults to current selection." })),
      style: Type.Optional(Type.String({ description: "Built-in or custom Word style name to apply." })),
      alignment: Type.Optional(Type.String({ description: "Paragraph alignment: left, centered, right, or justified." })),
      font: Type.Optional(Type.Object({
        name: Type.Optional(Type.String()),
        size: Type.Optional(Type.Number()),
        color: Type.Optional(Type.String()),
        bold: Type.Optional(Type.Boolean()),
        italic: Type.Optional(Type.Boolean()),
        underline: Type.Optional(Type.String()),
        highlightColor: Type.Optional(Type.String()),
      })),
      paragraph: Type.Optional(Type.Object({
        leftIndent: Type.Optional(Type.Number()),
        rightIndent: Type.Optional(Type.Number()),
        firstLineIndent: Type.Optional(Type.Number()),
        lineSpacing: Type.Optional(Type.Number()),
        spaceBefore: Type.Optional(Type.Number()),
        spaceAfter: Type.Optional(Type.Number()),
      })),
      clearFormatting: Type.Optional(Type.Boolean({ description: "Clear direct formatting on the target range before applying other options." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_list_format",
    hosts: ["word"],
    category: "write-doc",
    label: "Format Word List",
    description:
      "Word-only structured list formatting for converting selected or anchored paragraphs to bullets/numbering, changing levels, and removing numbering where Word desktop list APIs are available.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.list", "word.numbering", "word.outline"],
      keywords: ["word", "list", "bullet", "numbering", "outline", "indent", "outdent", "legal"],
      summary: "Apply Word list formatting through desktop-gated list APIs with explicit anchors.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApiDesktop", minVersion: "1.3", note: "ListFormat APIs are desktop-gated." }],
      fallback: "Use edit_doc_list or office_propose_edits for reviewable text-only list wording when list APIs are unavailable.",
    },
    parameters: Type.Object({
      target: Type.Optional(Type.Any({ description: "Optional Word anchor such as selection, paragraph, heading, or searchResult." })),
      operation: Type.String({ description: "bullet, number, outlineNumber, indent, outdent, removeNumbers, or setLevel." }),
      level: Type.Optional(Type.Number({ minimum: 1, maximum: 9, description: "List level for setLevel." })),
      confirmed: Type.Optional(Type.Boolean({ description: "Required for broad legal/contract renumbering or removeNumbers operations." })),
      legalSensitive: Type.Optional(Type.Boolean({ description: "Set true for contracts, legal clauses, or other numbering-sensitive documents." })),
      returnProposalsOnUnsupported: Type.Optional(Type.Boolean({ description: "Return reviewable text-edit fallback proposals when native list APIs are unavailable. Defaults to true." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_reference_inventory",
    hosts: ["word"],
    category: "read",
    label: "Word Reference Anchors",
    description: "Inventory or manage desktop-gated Word bookmarks and reference anchors for deterministic long-document navigation.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.bookmarks", "word.navigation", "word.anchors"],
      keywords: ["word", "bookmark", "anchor", "go to", "navigation", "reference"],
      summary: "Use Word bookmarks as durable long-document anchors where desktop APIs support them.",
      riskLevel: "low",
      requirementSets: [{ name: "WordApiDesktop", minVersion: "1.4", note: "Bookmark APIs are desktop-gated." }],
      fallback: "Use word_search searchResult anchors when desktop bookmark APIs are unavailable.",
    },
    parameters: Type.Object({
      operation: Type.Optional(Type.String({ description: "inventory, add, delete, select, or exists." })),
      name: Type.Optional(Type.String({ description: "Bookmark name for add/delete/select/exists." })),
      target: Type.Optional(Type.Any({ description: "Optional Word anchor used when creating a bookmark." })),
      preserve: Type.Optional(Type.Boolean({ description: "Whether generated bookmarks should be preserved rather than treated as temporary anchors." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_hyperlink",
    hosts: ["word"],
    category: "write-doc",
    label: "Word Hyperlink",
    description: "Add, update, remove, or inspect Word hyperlinks with explicit address, sub-address, display text, and screen-tip fields.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.hyperlinks", "word.navigation", "word.anchors"],
      keywords: ["word", "hyperlink", "link", "url", "screen tip", "cross reference"],
      summary: "Manage Word hyperlinks without raw OOXML or raw Office.js.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApiDesktop", minVersion: "1.3", note: "Hyperlink APIs are desktop-gated." }],
      fallback: "Use reviewable text proposals for visible URL text when desktop hyperlink APIs are unavailable.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "inventory, add, update, remove, or select." }),
      target: Type.Optional(Type.Any({ description: "Word anchor or hyperlink anchor to target." })),
      address: Type.Optional(Type.String({ description: "Hyperlink URL or file address." })),
      subAddress: Type.Optional(Type.String({ description: "Named location in the target document." })),
      textToDisplay: Type.Optional(Type.String({ description: "Visible hyperlink text." })),
      screenTip: Type.Optional(Type.String({ description: "Screen tip shown on hover." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_table",
    hosts: ["word"],
    category: "write-doc",
    label: "Edit Word Table",
    description:
      "Word-only structured table operations for inventory, cell text, rows/columns, styles, shading, merge, and delete with explicit destructive confirmation.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.tables", "word.tableCells", "word.tableRows"],
      keywords: ["word", "table", "cell", "row", "column", "merge", "shading", "style"],
      summary: "Inspect and mutate Word tables with precise coordinates instead of whole OOXML rewrites.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.3" }],
      fallback: "Use insertTable for simple table creation or reviewable proposals if table APIs are unavailable.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "inventory, setCellText, addRows, addColumns, deleteRows, deleteColumns, mergeCells, formatTable, or deleteTable." }),
      tableIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based table index. Defaults to 1." })),
      rowIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based row index for cell/row operations." })),
      columnIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based column index for cell/column operations." })),
      text: Type.Optional(Type.String({ description: "Cell replacement text for setCellText." })),
      values: Type.Optional(Type.Any({ description: "Optional 2D string values for inserted rows/columns." })),
      count: Type.Optional(Type.Number({ minimum: 1, description: "Rows/columns to add/delete. Defaults to 1." })),
      style: Type.Optional(Type.String({ description: "Custom/localized table style name." })),
      styleBuiltIn: Type.Optional(Type.String({ description: "Built-in table style name when supported." })),
      shadingColor: Type.Optional(Type.String({ description: "Table shading color, such as #F3F4F6." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Required for delete row/column/table operations." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_section_layout",
    hosts: ["word"],
    category: "write-doc",
    label: "Word Sections and Headers",
    description:
      "Word-only structured section, header/footer, page setup, and break operations with explicit section scope.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.sections", "word.headers", "word.footers", "word.pageSetup"],
      keywords: ["word", "section", "header", "footer", "page setup", "margin", "break"],
      summary: "Inspect and update Word section layout, headers, footers, margins, and breaks.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
      fallback: "Use document-body proposals only for visible body content; never imply body edits change headers/footers.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "inventory, setHeader, setFooter, clearHeader, clearFooter, pageSetup, or insertBreak." }),
      sectionIndex: Type.Optional(Type.Number({ minimum: 1, description: "One-based section index. Defaults to 1." })),
      headerFooterType: Type.Optional(Type.String({ description: "primary, firstPage, or evenPages. Defaults to primary." })),
      text: Type.Optional(Type.String({ description: "Header/footer text for setHeader or setFooter." })),
      margins: Type.Optional(Type.Any({ description: "Margin/page setup values in points: top, bottom, left, right, pageWidth, pageHeight." })),
      topMargin: Type.Optional(Type.Number({ description: "Top margin in points for pageSetup." })),
      bottomMargin: Type.Optional(Type.Number({ description: "Bottom margin in points for pageSetup." })),
      leftMargin: Type.Optional(Type.Number({ description: "Left margin in points for pageSetup." })),
      rightMargin: Type.Optional(Type.Number({ description: "Right margin in points for pageSetup." })),
      pageWidth: Type.Optional(Type.Number({ description: "Page width in points for pageSetup." })),
      pageHeight: Type.Optional(Type.Number({ description: "Page height in points for pageSetup." })),
      orientation: Type.Optional(Type.String({ description: "Page orientation: portrait or landscape." })),
      breakType: Type.Optional(Type.String({ description: "page, sectionNext, sectionContinuous, sectionEven, sectionOdd, or line." })),
      placement: Type.Optional(Type.String({ description: "Break placement: before, after, start, or end." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_field_reference",
    hosts: ["word"],
    category: "write-doc",
    label: "Word Fields and References",
    description:
      "Word-only structural field and table-of-contents operations for inventory, insert, update, lock/unlock, unlink, and page-number refresh workflows.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.fields", "word.toc", "word.references"],
      keywords: ["word", "field", "toc", "table of contents", "citation", "bibliography", "reference"],
      summary: "Manage Word fields and generated reference structures without corrupting field codes.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.4" }],
      fallback: "Use reviewable proposals for plain text only; never fabricate bibliography sources.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "inventory, insertField, updateField, lockField, unlockField, unlinkField, selectField, tocInventory, or updateTocPageNumbers." }),
      fieldId: Type.Optional(Type.String({ description: "Field anchor ID such as field:2." })),
      fieldType: Type.Optional(Type.String({ description: "Field type for insertField, for example TOC, REF, PAGE, or CITATION." })),
      fieldText: Type.Optional(Type.String({ description: "Field code/instruction text for insertion." })),
      target: Type.Optional(Type.Any({ description: "Optional insertion or field target anchor." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Required for unlinkField because it converts the field to static result text." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_content_control",
    hosts: ["word"],
    category: "write-doc",
    label: "Word Content Controls",
    description:
      "Inventory, fill, clear, update metadata, lock, select, or delete Word content controls by explicit ID/title/tag anchors for template automation.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.contentControls", "word.templates"],
      keywords: ["word", "content control", "template", "placeholder", "form", "tag", "title", "lock"],
      summary: "Fill and maintain Word template placeholders through explicit content-control anchors.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
      fallback: "Use word_search and reviewable proposals when content-control anchors are unavailable.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "inventory, fill, clear, setMetadata, lock, unlock, select, deleteWrapper, or deleteContent." }),
      target: Type.Optional(Type.Any({ description: "Content-control anchor. Prefer id like contentControl:123, title, or tag." })),
      title: Type.Optional(Type.String({ description: "Title to find or set." })),
      tag: Type.Optional(Type.String({ description: "Tag to find or set." })),
      text: Type.Optional(Type.String({ description: "Text to insert for fill." })),
      placeholderText: Type.Optional(Type.String({ description: "Placeholder text to set." })),
      cannotEdit: Type.Optional(Type.Boolean({ description: "Set content edit lock." })),
      cannotDelete: Type.Optional(Type.Boolean({ description: "Set wrapper delete lock." })),
      removeWhenEdited: Type.Optional(Type.Boolean({ description: "Remove wrapper after editing where supported." })),
      confirmDestructive: Type.Optional(Type.Boolean({ description: "Required for deleteContent." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_building_block",
    hosts: ["word"],
    category: "write-doc",
    label: "Word Building Blocks",
    description:
      "Inventory templates/building blocks and insert approved reusable Word content only when native desktop APIs expose it.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.buildingBlocks", "word.templates"],
      keywords: ["word", "template", "building block", "boilerplate", "clause", "quick parts"],
      summary: "Use approved Word reusable content with provenance instead of inventing boilerplate.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApiDesktop", minVersion: "1.3", note: "Building block/template APIs are desktop-gated." }],
      fallback: "Ask the user to provide approved boilerplate text when native building-block inventory is unavailable.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "inventory or insertApprovedText." }),
      name: Type.Optional(Type.String({ description: "Approved building-block/template entry name or user-provided source label." })),
      text: Type.Optional(Type.String({ description: "User-provided approved reusable content for insertApprovedText fallback." })),
      target: Type.Optional(Type.Any({ description: "Optional Word anchor where the reusable content should be inserted." })),
      placement: Type.Optional(Type.String({ description: "Insertion placement. Defaults to replace/after according to host action semantics." })),
      provenance: Type.Optional(Type.String({ description: "Required provenance/source note for user-provided boilerplate." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_annotation_review",
    hosts: ["word"],
    category: "write-doc",
    label: "Word Native Review Annotations",
    description:
      "Insert, inspect, accept, reject, or clear Word critique annotations when WordApi 1.7/1.8 support is available, with fallback to reviewable proposals.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.annotations", "word.review", "word.critiques"],
      keywords: ["word", "annotation", "critique", "review", "highlight", "suggestion"],
      summary: "Use Word-native critique annotations for supported hosts and fall back to proposal cards elsewhere.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.7", note: "Native critique annotations may require Microsoft 365 service support." }],
      fallback: "Use office_propose_edits when native annotation insertion is unavailable.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "insert, list, accept, reject, delete, or fallbackProposal." }),
      target: Type.Optional(Type.Any({ description: "Word anchor for the paragraph/range to annotate." })),
      critiques: Type.Optional(Type.Array(Type.Any(), { description: "Critique payloads with start, length, colorScheme, title, message, and suggestions." })),
      annotationId: Type.Optional(Type.String({ description: "Annotation ID for accept/reject/delete." })),
      fallbackEdits: Type.Optional(Type.Any({ description: "Reviewable edit proposal payload for unsupported native annotations." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "word_redline_review",
    hosts: ["word"],
    category: "write-doc",
    label: "Word Redline and Review Exchange",
    description:
      "Inspect tracked-review state and run desktop-gated Word compare/review exchange operations with explicit confirmation for broad review-state changes.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.compare", "word.redline", "word.reviewExchange"],
      keywords: ["word", "compare", "redline", "review", "tracked changes", "baseline"],
      summary: "Use Word-native comparison/review exchange workflows where supported; otherwise preserve review boundaries.",
      riskLevel: "high",
      requirementSets: [{ name: "WordApiDesktop", minVersion: "1.4", note: "Document compare and reviewer filters are desktop-gated." }],
      fallback: "Use verify_doc and existing revision accept/reject tools when compare/review exchange APIs are unavailable.",
    },
    parameters: Type.Object({
      operation: Type.String({ description: "diagnostics, compare, acceptAll, rejectAll, or endReview." }),
      baselinePath: Type.Optional(Type.String({ description: "Explicit local file path to compare against for desktop Word compare." })),
      confirmReviewStateChange: Type.Optional(Type.Boolean({ description: "Required for broad accept/reject/end-review operations." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "edit_doc_text",
    hosts: ["word"],
    category: "write-doc",
    label: "Edit Word Text",
    description: "Word-only first-class text editing. Use for direct clause/sentence updates through native Word actions when no per-edit review card is required.",
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.text", "word.formatting", "word.anchors"],
      keywords: ["word", "text", "clause", "sentence", "native edit", "paragraph", "selection"],
      summary: "Apply direct Word-native text edits to selections or structured anchors.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
      fallback: "Use office_propose_edits when the user should review each change before apply.",
    },
    parameters: Type.Object({
      mode: Type.Optional(Type.String({ description: "Legacy edit mode such as replaceSelection, insertAfterSelection, or setRangeValues." })),
      content: Type.Optional(Type.String({ description: "Legacy text, HTML, or JSON matrix payload to insert into Office." })),
      text: Type.Optional(Type.String({ description: "Alias for legacy text content. Use when operation/type is insertText." })),
      html: Type.Optional(Type.String({ description: "Alias for legacy HTML content. Use when operation/type is insertHtml." })),
      format: Type.Optional(Type.String({ description: "Legacy content format such as text, html, or matrix." })),
      operation: Type.Optional(Type.String({ description: "Top-level action type alias, e.g., insertText, insertHtml, setRangeValues." })),
      type: Type.Optional(Type.String({ description: "Top-level action type alias when not wrapping with action.type." })),
      values: Type.Optional(Type.Any({ description: "2D array of values for setRangeValues actions." })),
      action: Type.Optional(Type.Any({ description: "Structured OfficeHostAction payload. Use this for precise host-specific actions." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "office_read_section",
    hosts: ["word"],
    category: "read",
    label: "Read Document Section",
    description: "Read a paginated range of Word paragraphs by paragraph index.",
    discovery: {
      tier: "core",
      capabilityIds: ["word.read", "word.sections"],
      keywords: ["word", "read", "paragraph", "section", "page", "document"],
      summary: "Read a bounded paragraph window from a Word document without mutating it.",
      riskLevel: "low",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
    },
    parameters: Type.Object({
      startIndex: Type.Optional(Type.Number({ description: "Zero-based paragraph start index (inclusive)." })),
      endIndex: Type.Optional(Type.Number({ description: "Zero-based paragraph end index (exclusive). Defaults to startIndex + 20." })),
      start: Type.Optional(Type.Number({ description: "Alias for startIndex." })),
      end: Type.Optional(Type.Number({ description: "Alias for endIndex." })),
      includeStyles: Type.Optional(Type.Boolean({ description: "Include paragraph styles and heading levels. Defaults to true." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "verify_doc",
    hosts: ["word"],
    category: "read",
    label: "Verify Word Document",
    description: "Collect a non-mutating, structured Word verification context with summary text and detailed anchors/snippets for document checks.",
    discovery: {
      tier: "core",
      capabilityIds: ["word.verify", "word.read", "word.anchors"],
      keywords: ["word", "verify", "review", "anchors", "comments", "revisions", "fields", "content controls"],
      summary: "Collect non-mutating Word verification context with anchors and formatting metadata.",
      riskLevel: "low",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
    },
    parameters: Type.Object({
      scope: Type.Optional(Type.String({ description: "Verification target for Word context capture (selection or document). Defaults to document-level verification context." })),
      includeFormatting: Type.Optional(Type.Boolean({ description: "Include formatting metadata in the verification payload. Defaults to true." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "verify_doc_visual",
    hosts: ["word"],
    category: "read",
    label: "Verify Word Visual",
    description: "Capture non-mutating Word visual verification context through the supported viewport path. Word-only; returns structured visual/details payloads.",
    discovery: {
      tier: "core",
      capabilityIds: ["word.verify", "word.visual"],
      keywords: ["word", "visual", "layout", "viewport", "formatting", "snapshot"],
      summary: "Capture Word visual/formatting verification through Office.js context and available companion metadata.",
      riskLevel: "low",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
      fallback: "Use office_get_context for text-only verification when visual capture is unavailable.",
    },
    parameters: Type.Object({
      includeFormatting: Type.Optional(Type.Boolean({ description: "Include formatting metadata in the visual payload. Defaults to true." })),
      includeWindowFrame: Type.Optional(Type.Boolean({ description: "Request window-frame metadata when a companion native capture is available." })),
    }),
    executor: "office-bridge",
  },
  {
    name: "edit_doc_list",
    hosts: ["word"],
    category: "write-doc",
    label: "Edit Word List",
    description: `Word-only first-class reviewable list editing. Keep each searchText under ${OFFICE_PROPOSE_EDITS_SEARCH_TEXT_MAX_LENGTH} characters and include paragraphId/anchor locators when available.`,
    discovery: {
      tier: "specialized",
      capabilityIds: ["word.list", "word.review"],
      keywords: ["word", "list", "bullet", "numbering", "legal", "review", "proposal"],
      summary: "Prepare reviewable Word list edits with deterministic short search targets.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
      fallback: "Use office_propose_edits for non-list reviewable text edits.",
    },
    parameters: proposeEditsParams,
    executor: "reviewable-word-edit",
    deferred: true,
  },
  {
    name: "office_propose_edits",
    hosts: ["word"],
    category: "write-doc",
    label: "Propose Document Edits",
    description:
      `Propose a batch of text edits for user review before applying changes. ` +
      `CRITICAL: each edit's searchText MUST be under ${OFFICE_PROPOSE_EDITS_SEARCH_TEXT_MAX_LENGTH} characters. ` +
      "Split large paragraph rewrites into multiple small, targeted edits.",
    discovery: {
      tier: "core",
      capabilityIds: ["word.review", "word.text"],
      keywords: ["word", "proposal", "review", "tracked", "redline", "replace", "delete", "insert"],
      summary: "Show reviewable Word edit cards before applying targeted text changes.",
      riskLevel: "medium",
      requirementSets: [{ name: "WordApi", minVersion: "1.1" }],
    },
    parameters: proposeEditsParams,
    executor: "reviewable-word-edit",
    deferred: true,
  },
];
