import type {
  ConnectorCatalogItem,
  ConnectorCategory,
  ConnectorConfigTemplate,
  ConnectorEnvHint,
  ConnectorReadPolicy,
  ConnectorRuntimeRequirement,
} from "@pi-office/pi-office-pack";

type CatalogEntry = ConnectorCatalogItem & { priority: number };
const CATALOG_REVISION = "2026-04-02";

const DEFAULT_ALLOW_PATTERNS = [
  "^(get|list|search|find|read|fetch|query|retrieve|describe|preview|inspect|lookup|resolve|show|view|count|whoami|stat)",
  "(^|_)(search|list|get|read|find|fetch|query|describe|inspect|preview|lookup|retrieve)(_|$)",
];

const DEFAULT_BLOCK_PATTERNS = [
  "^(create|update|delete|remove|write|edit|insert|append|upload|post|put|patch|merge|commit|apply|send|message|reply|comment|close|reopen|archive|move|rename|grant|revoke|start|stop|restart|approve|reject|refund|charge|pay)",
  "(^|_)(create|update|delete|remove|write|edit|insert|append|upload|post|put|patch|merge|commit|apply|send|message|reply|comment|close|reopen|archive|move|rename|grant|revoke|start|stop|restart|approve|reject|refund|charge|pay)(_|$)",
];

function readPolicy(extraBlocked: string[] = [], extraAllowed: string[] = []): ConnectorReadPolicy {
  return {
    mode: "hard-read-only",
    allowResources: true,
    allowPrompts: false,
    allowToolPatterns: [...DEFAULT_ALLOW_PATTERNS, ...extraAllowed],
    blockToolPatterns: [...DEFAULT_BLOCK_PATTERNS, ...extraBlocked],
    allowPromptPatterns: [],
    blockPromptPatterns: [".*"],
  };
}

function envHints(...keys: Array<[string, string, string?, boolean?]>): ConnectorEnvHint[] {
  return keys.map(([key, label, description, required]) => ({
    key,
    label,
    description,
    required,
  }));
}

function reqs(...entries: Array<[ConnectorRuntimeRequirement["key"], string, boolean?, string?]>): ConnectorRuntimeRequirement[] {
  return entries.map(([key, label, optional, description]) => ({
    key,
    label,
    optional,
    description,
  }));
}

function template(template: ConnectorConfigTemplate): ConnectorConfigTemplate {
  return template;
}

function connector(
  priority: number,
  category: ConnectorCategory,
  item: Omit<CatalogEntry, "priority" | "category" | "recommendedHosts" | "setupDifficulty" | "catalogRevision"> &
    Partial<Pick<ConnectorCatalogItem, "recommendedHosts" | "setupDifficulty" | "catalogRevision">>,
): CatalogEntry {
  return {
    priority,
    category,
    recommendedHosts: item.recommendedHosts ?? ["word", "excel", "powerpoint"],
    setupDifficulty:
      item.setupDifficulty ??
      (item.customOnly ? "advanced" : item.setupKind === "local_node" || item.setupKind === "local_python" ? "guided" : "easy"),
    catalogRevision: item.catalogRevision ?? CATALOG_REVISION,
    ...item,
  };
}

const CATALOG: CatalogEntry[] = [
  connector(10, "knowledge", {
    id: "jira",
    name: "Jira",
    vendor: "Atlassian",
    iconKey: "jira",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read issues, epics, comments, and sprint context while drafting updates or preparing status reports.",
    officeValue: "Pull project status into executive summaries, RAID logs, and meeting notes without copying tickets manually.",
    tags: ["tickets", "project-tracking", "status"],
    capabilityHints: ["search issues", "read ticket details", "review comments"],
    requirements: [],
    envHints: envHints(["JIRA_API_TOKEN", "Jira API token", "Reuse an existing Jira token from this PC."], ["JIRA_BASE_URL", "Jira site URL", "For example https://your-team.atlassian.net", true]),
    readPolicy: readPolicy(["(^|_)(transition|assign|comment|edit|create_issue|update_issue)(_|$)"]),
    docsUrl: "https://www.atlassian.com/software/jira",
    authUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
    setupNotes: [
      "Most Jira MCP servers use a site URL plus an API token.",
      "Use read-only access for reporting and drafting only.",
    ],
  }),
  connector(11, "knowledge", {
    id: "confluence",
    name: "Confluence",
    vendor: "Atlassian",
    iconKey: "confluence",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Search wiki pages, SOPs, and project documentation while writing polished Office documents.",
    officeValue: "Ground slide decks, briefs, and meeting notes in the latest internal documentation.",
    tags: ["wiki", "knowledge-base", "docs"],
    capabilityHints: ["search pages", "read page content", "fetch spaces"],
    requirements: [],
    envHints: envHints(["CONFLUENCE_API_TOKEN", "Confluence API token"], ["CONFLUENCE_BASE_URL", "Confluence site URL", "For example https://your-team.atlassian.net/wiki", true]),
    readPolicy: readPolicy(["(^|_)(create_page|update_page|delete_page|comment|publish)(_|$)"]),
    docsUrl: "https://www.atlassian.com/software/confluence",
    authUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
    setupNotes: [
      "Use a site URL and token pair.",
      "Confluence works best for policy docs, specs, and meeting follow-ups.",
    ],
  }),
  connector(12, "productivity", {
    id: "microsoft-365",
    name: "Microsoft 365 (Work IQ)",
    vendor: "Microsoft",
    iconKey: "microsoft-365",
    maturity: "beta",
    setupKind: "remote_oauth",
    authMethod: "oauth",
    transport: "remote_http",
    readOnly: true,
    summary: "Read Teams channels, SharePoint files, Outlook email, calendar events, and OneDrive documents through Microsoft's official Work IQ MCP.",
    officeValue: "Ground your Office documents in real M365 context: meeting notes from Teams, source files from SharePoint, and email threads from Outlook.",
    tags: ["m365", "teams", "sharepoint", "email", "calendar", "files", "onedrive"],
    capabilityHints: ["search Teams messages", "read SharePoint files", "list calendar events", "search email", "browse OneDrive"],
    requirements: [],
    envHints: envHints(["M365_ACCESS_TOKEN", "Microsoft 365 access token", "If you already export a token locally, the add-in can reuse it."]),
    readPolicy: readPolicy(["(^|_)(send|message|reply|post|upload|delete|move|rename|share|grant|create|write|create_channel)(_|$)"]),
    docsUrl: "https://github.com/microsoft/work-iq",
    authUrl: "https://portal.office.com",
    setupNotes: [
      "Work IQ is Microsoft's official MCP server for M365 productivity data.",
      "Use browser sign-in or a Microsoft 365 access token from your IT-approved flow.",
      "Covers Teams, SharePoint, Calendar, Email, and OneDrive in a single connector.",
    ],
  }),
  connector(13, "engineering", {
    id: "figma",
    name: "Figma",
    vendor: "Figma",
    iconKey: "figma",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read design files, comments, and handoff context while preparing specs or reviews.",
    officeValue: "Reference source-of-truth design decisions when building product decks and feature briefs.",
    tags: ["design", "handoff", "review"],
    capabilityHints: ["read file metadata", "inspect comments", "search design context"],
    requirements: [],
    envHints: envHints(["FIGMA_API_KEY", "Figma token"]),
    readPolicy: readPolicy(["(^|_)(create|update|delete|comment|post)(_|$)"]),
    docsUrl: "https://www.figma.com/developers/api",
    authUrl: "https://www.figma.com/developers/api",
    setupNotes: [
      "Use a personal access token or your approved workspace token.",
    ],
  }),

  connector(15, "collaboration", {
    id: "slack",
    name: "Slack",
    vendor: "Slack",
    iconKey: "slack",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "bearer_token",
    transport: "remote_http",
    readOnly: true,
    summary: "Read channels, threads, and searchable message history from Slack workspaces.",
    officeValue: "Summarize scattered decisions into crisp Office-ready outputs without manually copying message threads.",
    tags: ["chat", "threads", "search"],
    capabilityHints: ["search messages", "read channels", "inspect threads"],
    requirements: [],
    envHints: envHints(["SLACK_BOT_TOKEN", "Slack bot token"], ["SLACK_USER_TOKEN", "Slack user token"]),
    readPolicy: readPolicy(["(^|_)(chat_post|post_message|reply|send|create_channel|archive)(_|$)"]),
    docsUrl: "https://api.slack.com",
    authUrl: "https://api.slack.com/apps",
    setupNotes: [
      "Most Slack MCP servers use a bot or user token.",
      "Choose a token with read scopes only when possible.",
    ],
  }),
  connector(16, "knowledge", {
    id: "notion",
    name: "Notion",
    vendor: "Notion",
    iconKey: "notion",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "bearer_token",
    transport: "remote_http",
    readOnly: true,
    summary: "Search pages, databases, and notes from shared Notion workspaces.",
    officeValue: "Useful for pulling fast-moving planning notes into polished documents and presentations.",
    tags: ["notes", "wiki", "database"],
    capabilityHints: ["search pages", "read databases", "inspect notes"],
    requirements: [],
    envHints: envHints(["NOTION_API_KEY", "Notion internal integration token"]),
    readPolicy: readPolicy(["(^|_)(create_page|update_page|append|write)(_|$)"]),
    docsUrl: "https://developers.notion.com",
    authUrl: "https://www.notion.so/my-integrations",
    setupNotes: [
      "Use an internal integration token that already has page access granted.",
    ],
  }),
  connector(17, "knowledge", {
    id: "obsidian",
    name: "Obsidian",
    vendor: "Obsidian",
    iconKey: "obsidian",
    maturity: "custom_mcp_only",
    setupKind: "local_executable_or_docker",
    authMethod: "none",
    transport: "local_stdio",
    readOnly: true,
    customOnly: true,
    summary: "Connect a local Obsidian MCP if your team already has one.",
    officeValue: "Helpful for private research vaults and note libraries that are already curated locally.",
    tags: ["local", "notes", "vault"],
    capabilityHints: ["search notes", "read vault content"],
    requirements: reqs(["node", "Node.js"], ["npx", "npx"]),
    envHints: [],
    readPolicy: readPolicy(["(^|_)(append|write|rename|move|delete)(_|$)"]),
    docsUrl: "https://obsidian.md",
    setupNotes: [
      "Obsidian setups vary heavily, so this starts in guided custom mode.",
    ],
  }),
  connector(18, "knowledge", {
    id: "granola",
    name: "Granola",
    vendor: "Granola",
    iconKey: "granola",
    maturity: "custom_mcp_only",
    setupKind: "remote_url_token",
    authMethod: "bearer_token",
    transport: "remote_http",
    readOnly: true,
    customOnly: true,
    summary: "Use a custom Granola MCP if your workspace exposes one.",
    officeValue: "Meeting notes and summaries can become source material for proposals and action docs.",
    tags: ["meetings", "notes"],
    capabilityHints: ["read meetings", "search notes"],
    requirements: [],
    envHints: envHints(["GRANOLA_API_KEY", "Granola token"]),
    readPolicy: readPolicy(),
    docsUrl: "https://www.granola.ai",
    setupNotes: [
      "No default MCP template ships yet. Use the custom connector wizard.",
    ],
  }),
  connector(19, "knowledge", {
    id: "supermemory",
    name: "Supermemory",
    vendor: "Supermemory",
    iconKey: "supermemory",
    maturity: "custom_mcp_only",
    setupKind: "remote_url_token",
    authMethod: "bearer_token",
    transport: "remote_http",
    readOnly: true,
    customOnly: true,
    summary: "Connect a hosted Supermemory MCP if your team uses it for memory and retrieval.",
    officeValue: "Useful for quickly grounding drafts in prior conversations or indexed knowledge.",
    tags: ["memory", "retrieval"],
    capabilityHints: ["search memories", "retrieve saved context"],
    requirements: [],
    envHints: envHints(["SUPERMEMORY_API_KEY", "Supermemory token"]),
    readPolicy: readPolicy(),
    docsUrl: "https://supermemory.ai",
    setupNotes: ["Starts in custom setup until a stable template is confirmed."],
  }),
  connector(20, "analytics", {
    id: "posthog",
    name: "PostHog",
    vendor: "PostHog",
    iconKey: "posthog",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read product analytics, dashboards, and event trends while building reviews or product updates.",
    officeValue: "Ground roadmap decks and review docs in live usage data.",
    tags: ["analytics", "product", "usage"],
    capabilityHints: ["query dashboards", "read insights", "inspect events"],
    requirements: [],
    envHints: envHints(["POSTHOG_API_KEY", "PostHog personal API key"], ["POSTHOG_BASE_URL", "PostHog host URL", "Needed for self-hosted workspaces."]),
    readPolicy: readPolicy(["(^|_)(capture|create|update|delete|feature_flag_update)(_|$)"]),
    docsUrl: "https://posthog.com/docs",
    authUrl: "https://app.posthog.com/settings/user-api-keys",
  }),
  connector(21, "analytics", {
    id: "launchdarkly",
    name: "LaunchDarkly",
    vendor: "LaunchDarkly",
    iconKey: "launchdarkly",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read flag states, environments, and rollout context from LaunchDarkly.",
    officeValue: "Ideal for release notes, rollout plans, and operational review slides.",
    tags: ["feature-flags", "release"],
    capabilityHints: ["list flags", "inspect environments", "review rollout metadata"],
    requirements: [],
    envHints: envHints(["LAUNCHDARKLY_API_KEY", "LaunchDarkly access token"]),
    readPolicy: readPolicy(["(^|_)(patch|update|delete|create|toggle|archive)(_|$)"]),
    docsUrl: "https://launchdarkly.com/docs",
    authUrl: "https://app.launchdarkly.com/settings/authorization/tokens",
  }),
  connector(22, "commerce", {
    id: "shopify",
    name: "Shopify",
    vendor: "Shopify",
    iconKey: "shopify",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read products, orders, and store metrics for merchant-facing documents.",
    officeValue: "Useful for merchandising reports, launch decks, and customer success recaps.",
    tags: ["commerce", "orders", "catalog"],
    capabilityHints: ["list orders", "read products", "inspect store data"],
    requirements: [],
    envHints: envHints(["SHOPIFY_ACCESS_TOKEN", "Shopify Admin API token"], ["SHOPIFY_STORE_DOMAIN", "Shopify store domain"]),
    readPolicy: readPolicy(["(^|_)(fulfill|refund|update|delete|create|adjust)(_|$)"]),
    docsUrl: "https://shopify.dev",
    authUrl: "https://shopify.dev/apps",
  }),
  connector(23, "commerce", {
    id: "stripe",
    name: "Stripe",
    vendor: "Stripe",
    iconKey: "stripe",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read payments, subscriptions, and billing context for finance or operations work.",
    officeValue: "Helpful for business reviews, reconciliations, and executive finance summaries.",
    tags: ["payments", "billing", "finance"],
    capabilityHints: ["read charges", "list customers", "inspect subscriptions"],
    requirements: [],
    envHints: envHints(["STRIPE_API_KEY", "Stripe secret key"]),
    readPolicy: readPolicy(["(^|_)(refund|capture|create|update|delete|cancel)(_|$)"]),
    docsUrl: "https://docs.stripe.com",
    authUrl: "https://dashboard.stripe.com/apikeys",
  }),
  connector(24, "commerce", {
    id: "paypal",
    name: "PayPal",
    vendor: "PayPal",
    iconKey: "paypal",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read PayPal transaction and payout context for finance reporting.",
    officeValue: "Useful for payout summaries, payment investigations, and finance ops templates.",
    tags: ["payments", "finance"],
    capabilityHints: ["read transactions", "inspect payouts", "search payments"],
    requirements: [],
    envHints: envHints(["PAYPAL_ACCESS_TOKEN", "PayPal access token"], ["PAYPAL_CLIENT_ID", "PayPal client id"], ["PAYPAL_CLIENT_SECRET", "PayPal client secret"]),
    readPolicy: readPolicy(["(^|_)(refund|capture|create|update|cancel)(_|$)"]),
    docsUrl: "https://developer.paypal.com",
    authUrl: "https://developer.paypal.com/dashboard",
  }),
  connector(25, "data", {
    id: "airtable",
    name: "Airtable",
    vendor: "Airtable",
    iconKey: "airtable",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "bearer_token",
    transport: "remote_http",
    readOnly: true,
    summary: "Read tables, views, and linked records for operations and planning workflows.",
    officeValue: "Great for status trackers, launch plans, hiring ops, and structured planning data in Office docs.",
    tags: ["tables", "planning", "ops"],
    capabilityHints: ["list bases", "read records", "query views"],
    requirements: [],
    envHints: envHints(["AIRTABLE_API_KEY", "Airtable token"]),
    readPolicy: readPolicy(["(^|_)(create|update|delete|write|append)(_|$)"]),
    docsUrl: "https://airtable.com/developers/web/api/introduction",
    authUrl: "https://airtable.com/create/tokens",
  }),
  connector(26, "research", {
    id: "perplexity",
    name: "Perplexity",
    vendor: "Perplexity",
    iconKey: "perplexity",
    maturity: "custom_mcp_only",
    setupKind: "remote_url_token",
    authMethod: "bearer_token",
    transport: "remote_http",
    readOnly: true,
    customOnly: true,
    summary: "Use a hosted Perplexity MCP if your organization already runs one.",
    officeValue: "Useful for fast briefing support and web-grounded background research.",
    tags: ["research", "search"],
    capabilityHints: ["search web", "retrieve answers"],
    requirements: [],
    envHints: envHints(["PERPLEXITY_API_KEY", "Perplexity token"]),
    readPolicy: readPolicy(),
    docsUrl: "https://www.perplexity.ai",
    setupNotes: ["This entry starts in custom mode until a stable MCP template is confirmed."],
  }),
  connector(27, "research", {
    id: "parallel-web",
    name: "Parallel Web",
    vendor: "Parallel",
    iconKey: "parallel",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Read fresh web results from Parallel's search tooling.",
    officeValue: "Useful for market scans, competitive research, and cited briefing material.",
    tags: ["web", "search", "research"],
    capabilityHints: ["web fetch", "web search"],
    requirements: [],
    envHints: envHints(["PARALLEL_API_KEY", "Parallel API key"]),
    readPolicy: readPolicy(),
    docsUrl: "https://parallel.ai",
    setupNotes: ["Use an API key-backed hosted MCP endpoint if your team provides one."],
  }),
  connector(28, "research", {
    id: "exa-search",
    name: "Exa Search",
    vendor: "Exa",
    iconKey: "exa",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Use Exa-backed search and discovery for research-heavy documents.",
    officeValue: "Good for analyst notes, market maps, and supporting references in Office content.",
    tags: ["search", "research", "discovery"],
    capabilityHints: ["web search", "content discovery"],
    requirements: [],
    envHints: envHints(["EXA_API_KEY", "Exa API key"]),
    readPolicy: readPolicy(),
    docsUrl: "https://exa.ai",
  }),
  connector(29, "data", {
    id: "qdrant",
    name: "Qdrant",
    vendor: "Qdrant",
    iconKey: "qdrant",
    maturity: "beta",
    setupKind: "remote_url_token",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Query vector collections and retrieval layers that back internal knowledge systems.",
    officeValue: "Useful when Office docs need to reference internal RAG indexes or embeddings-based search.",
    tags: ["vector-db", "retrieval", "data"],
    capabilityHints: ["query collections", "search points", "inspect collections"],
    requirements: [],
    envHints: envHints(["QDRANT_API_KEY", "Qdrant API key"], ["QDRANT_URL", "Qdrant base URL"]),
    readPolicy: readPolicy(["(^|_)(upsert|delete|create_collection|update|write)(_|$)"]),
    docsUrl: "https://qdrant.tech/documentation/",
  }),
  connector(30, "productivity", {
    id: "google-drive",
    name: "Google Drive",
    vendor: "Google",
    iconKey: "gdrive",
    maturity: "beta",
    setupKind: "remote_oauth",
    authMethod: "oauth",
    transport: "remote_http",
    readOnly: true,
    summary: "Read shared Drive folders, Docs exports, and supporting files from Google Workspace.",
    officeValue: "Bring reference material from Drive into Microsoft Office writing workflows.",
    tags: ["files", "docs", "workspace"],
    capabilityHints: ["list files", "read file metadata", "search drive"],
    requirements: [],
    envHints: envHints(["GOOGLE_DRIVE_ACCESS_TOKEN", "Google access token"]),
    readPolicy: readPolicy(["(^|_)(upload|delete|move|rename|share|create|write)(_|$)"]),
    docsUrl: "https://developers.google.com/drive",
    authUrl: "https://console.cloud.google.com",
    setupNotes: [
      "Use browser sign-in or a pre-issued Google access token from your approved workflow.",
    ],
  }),
  connector(31, "engineering", {
    id: "github",
    name: "GitHub",
    vendor: "GitHub",
    iconKey: "github",
    maturity: "ready",
    setupKind: "local_node",
    authMethod: "bearer_token",
    transport: "local_stdio",
    readOnly: true,
    summary: "Read repositories, issues, pull requests, and discussions from GitHub.",
    officeValue: "Excellent for release notes, engineering reviews, and product updates assembled inside Office.",
    tags: ["code", "issues", "pull-requests"],
    capabilityHints: ["read repo files", "list PRs", "search issues"],
    requirements: reqs(["node", "Node.js"], ["npx", "npx"]),
    envHints: envHints(["GITHUB_PERSONAL_ACCESS_TOKEN", "GitHub personal access token", "Classic or fine-grained token with read scopes only when possible."]),
    readPolicy: readPolicy(["(^|_)(create_issue|create_pull|merge|close_pull|update|delete|comment|review|push)(_|$)"]),
    template: template({
      transport: "local_stdio",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-github"],
      env: {
        GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_PERSONAL_ACCESS_TOKEN}",
      },
    }),
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    authUrl: "https://github.com/settings/tokens",
    setupNotes: [
      "This is one of the most turnkey MCP setups for read-only knowledge access.",
    ],
  }),
  connector(32, "engineering", {
    id: "gitlab",
    name: "GitLab",
    vendor: "GitLab",
    iconKey: "gitlab",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "bearer_token",
    transport: "remote_http",
    readOnly: true,
    summary: "Read merge requests, issues, and project files from GitLab workspaces.",
    officeValue: "Useful for engineering status packs and stakeholder-facing release materials.",
    tags: ["code", "issues", "merge-requests"],
    capabilityHints: ["read files", "list merge requests", "inspect issues"],
    requirements: [],
    envHints: envHints(["GITLAB_PERSONAL_ACCESS_TOKEN", "GitLab personal access token"], ["GITLAB_BASE_URL", "GitLab base URL", "Required for self-hosted GitLab instances."]),
    readPolicy: readPolicy(["(^|_)(merge|approve|comment|create|update|delete|pipeline_run)(_|$)"]),
    docsUrl: "https://about.gitlab.com",
    authUrl: "https://gitlab.com/-/user_settings/personal_access_tokens",
  }),
  connector(33, "data", {
    id: "postgresql-reader",
    name: "PostgreSQL Reader",
    vendor: "PostgreSQL",
    iconKey: "postgres",
    maturity: "ready",
    setupKind: "local_node",
    authMethod: "api_key",
    transport: "local_stdio",
    readOnly: true,
    summary: "Run safe, read-only queries against Postgres data sources that back your reports and models.",
    officeValue: "Very effective for pulling live numbers into tables, summaries, and decision docs.",
    tags: ["sql", "database", "reporting"],
    capabilityHints: ["describe schema", "run SELECT queries", "inspect tables"],
    requirements: reqs(["node", "Node.js"], ["npx", "npx"]),
    envHints: envHints(["POSTGRES_CONNECTION_STRING", "Postgres connection string"]),
    readPolicy: readPolicy(["(^|_)(insert|update|delete|alter|drop|truncate|grant|revoke)(_|$)"]),
    template: template({
      transport: "local_stdio",
      command: "npx",
      args: ["-y", "@modelcontextprotocol/server-postgres"],
      env: {
        POSTGRES_CONNECTION_STRING: "${POSTGRES_CONNECTION_STRING}",
      },
    }),
    docsUrl: "https://github.com/modelcontextprotocol/servers",
    setupNotes: [
      "The add-in will still block non-read tools even if the underlying server exposes them.",
    ],
  }),
  connector(34, "research", {
    id: "tavily",
    name: "Tavily",
    vendor: "Tavily",
    iconKey: "tavily",
    maturity: "beta",
    setupKind: "remote_api_key",
    authMethod: "api_key",
    transport: "remote_http",
    readOnly: true,
    summary: "Use Tavily-backed search for fast research and fresh web retrieval.",
    officeValue: "Great for cited background research in briefs, decks, and customer-facing docs.",
    tags: ["web", "search", "research"],
    capabilityHints: ["web search", "fetch results"],
    requirements: [],
    envHints: envHints(["TAVILY_API_KEY", "Tavily API key"]),
    readPolicy: readPolicy(),
    docsUrl: "https://tavily.com",
  }),
];

export function listConnectorCatalog(): ConnectorCatalogItem[] {
  return [...CATALOG]
    .sort((left, right) => left.priority - right.priority || left.name.localeCompare(right.name))
    .map(({ priority: _priority, ...item }) => item);
}

export function getConnectorCatalogItem(connectorId: string): ConnectorCatalogItem | undefined {
  return listConnectorCatalog().find((item) => item.id === connectorId);
}
